### PR TITLE
Apple Clone

### PR DESCRIPTION
**Pull request by chindrop**
## Apple Clone Milestone:

In this project we;
- I built and fixed the navigation bar
- Gave the Nav some gradient
- And laid a background image

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @chindrop        
#### Great Job so far, but there is one more thing to do. 
### Navbar
- [ ] The navbar should look like the original site, let's fix that.


- [ ] It seems your Linters isn't working(Am not seeing **All checks have passed**), Please fix that.
.
### Make changes and submit another code review request.
*Happy coding*

**Comment by chindrop** [comment]
- Corrections to the Nav bar
- Gave the Nav some new gradient

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work @chindrop! :medal_military: 
You implemented all the changes requested by @kobiyoyo :clap:. Please consider updating the screenshot in your readme file but more importantly, your linter doesn't seem to be working and as such, I cannot approve your PR. Please look into it, make the required adjustments and request another review :+1: 

#### [OPTIONAL] Use of background images
Please consider that as per the requirements for this project, the images in the footer are supposed to be `<div>` tags with their `background-image` properties set to the image URL and not image tags inside divs
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by chindrop** [comment]
- Divs for background image adjusted
- Screenshot for readme updated

**Comment by chindrop** [comment]
- stickler in git repo not working so I used linter in my local env

**Review by nikasulo — APPROVED** [review]
# Great work @chindrop :medal_military: 
You may merge and keep moving forward. I know you ran eslint locally and fixed the errors, however, please consider looking into the challenge with getting stickler to function properly :handshake: I wish you all the best moving forward! See you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
